name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: ${{ secrets.DEPLOY_USERNAME }}
          server: ${{ secrets.DEPLOY_HOST }}
          ssh_private_key: ${{ secrets.DEPLOY_PASSWORD }}
          local_path: './public'
          remote_path: ${{ secrets.DEPLOY_DEST_PATH }}
          args: '-o ConnectTimeout=5'